services:
  data-pipeline-service:
    container_name: data-pipeline-service
    ports:
      - "30001:30001"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - PORT=30001

      - BE_AI_DATABASE_URL=${BE_AI_DATABASE_URL}

      - SUPABASE_PROJECT_ID=${SUPABASE_PROJECT_ID}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
      - VNPAY_HASH_SECRET_KEY=${VNPAY_HASH_SECRET_KEY}
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL}
      - VNPAY_PAYMENT_URL=${VNPAY_PAYMENT_URL}
      - VNPAY_API_URL=${VNPAY_API_URL}

      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=vbpl

      - HF_TOKEN=${HF_TOKEN}

      - NVIDIA_API_KEY=${NVIDIA_API_KEY}

      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}

      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
