services:
  data-pipeline-service:
    extends:
      file: docker-compose.base.yml
      service: data-pipeline-service
    build:
      context: "."
      dockerfile: "./Dockerfile.prod"

    # volumes:
    #   - "/app/.venv"
    # # command:  tail -f /dev/null
